### PR TITLE
Fix/reversed caches - with tests

### LINKED ISSUE #683: L1I  is swapped with the ITLB in `O3_CPU`
**Describe the bug**

I have been trying to make a prefetcher for the L1I and realized the `CACHE::prefetcher_branch_operate` function never got called. Then I noticed when running simulations, the L1I is swapped with the ITLB. In addition looking at `.csconfig/core_inst.cc.inc` the order of caches in `champsim.cc` should be:

0: LLC
1: cpu0_DTLB
2: cpu0_ITLB
3: cpu0_L1D
4: cpu0_L1I
5: cpu0_L2C
6: cpu0_STLB

In fact this order is reversed in the `champsim.cc`.

**To Reproduce**
1. Print the `NAME` of the caches in `champsim.cc` 
2. Print the `NAME` of l1i in `ooo_cpu.cc`

**Expected behavior**
 the l1i `CACHE::prefetcher_branch_operate`  in `ooo_cpu.cc`  should call the function for the L1I prefetcher not ITLB.

**Desktop (please complete the following information):**
 - OS:  6.12.63+deb13-amd64 \#1 SMP PREEMPT_DYNAMIC Debian 6.12.63-1 (2025-12-30) x86_64 GNU/Linux
 - Compiler gcc (Debian 14.2.0-19) 14.2.0
 - Version commit 06de8d3d03d9ba39b4726166aa6364881812365f

### PR DESCRIPTION
**Pull request by maccoymerrell**
This pr addresses issues identified by @aaarunan, adds testing, and replaces the forward_list containers with regular vectors.

To facilitate testing, the build() function which was previously defined in environment.cc had to be moved to environment.h.

### CODE REVIEW

File: inc/environment.h [hunk 1]
```diff
@@ -40,6 +40,14 @@ namespace configured
 {
 template <unsigned long long ID>
 struct generated_environment;
+
+template <typename R, typename... PTWs>
+auto build(PTWs... builders)
+{
+  std::vector<R> retval{};
```
Comment (ngober) [inline inc/environment.h:47]:
```suggestion
  std::vector<R> retval{};
  retval.reserve(sizeof...(builders));
```

I'm keeping #471 in the back of my mind. Reserving space in this vector will avoid moves caused by the emplace.

**Review by ngober — CHANGES_REQUESTED** [review]
I have a small change request.

**Review by ngober — APPROVED** [review]

**Comment by maccoymerrell** [comment]
> I have a small change request.

I wonder if having modules referenced exclusively by name would be worthwhile - we incur the overhead of the std::map string -> pointer conversion but it prevents modules from getting bad pointers (assuming that the map is maintained properly and everything is provided a unique name).

This also relies on enforcing that modules cannot and should not be moved after instantiation. Using a centralized system like what I am trying for module runtime selection could work - but it would need applied to everything.
I guess what I am saying is that moving pointers is probably better than moving actual objects, even when considering the de-reference cost.

**Comment by ngober** [comment]
I'm pretty averse to prohibiting moves. This is a philosophical position: an object's identity is not defined by its location in memory, it is defined by it's value (in the case of a cache, perhaps only its name, but also maybe it's contents). One should be able to construct it and move it around in memory without violating its identity. We're not quite there in ChampSim, but we're pretty close. Most of the time we look through queues to find an identity match. Anyway, that's a topic for another patch.
