### PR TITLE
Added downstream stats for cache, fixed cache miss latency calculations to use downstream.

### LINKED ISSUE #535: Cache miss latency misreporting
**Describe the bug**
When reporting the miss latency of the cache, it is done in the following way:
1. Record when a MSHR type is created, this becomes the "time_enqueued" value
2. When merging, "time_enqueued" is set to the predecessor when the successor is a prefetch and the successor otherwise
3. Total miss latency cycles is the sum of the differences between cycle when the MSHR is closed and the time enqueued.
4. The average miss latency is calculated by dividing this value by ALL cache misses

**Expected behavior**
Average miss latency should report the average lifespan of an MSHR entry.
By allowing time_enqueued to be altered when multiple demands merge into a MSHR, it reduces the apparent cache latency.
By dividing by the total misses to the cache, we reduce the apparent miss latency by counting MSHR merges towards our total count.

**What are we trying to track?**
It seems to me that its better to track miss latency by recording the total cycles MSHR entries stay open and dividing it by the number of miss (non-writeback) packets sent downstream.
It also seems more correct to only update the time_enqueued value from the initial MSHR entry if a demand merges into a prefetch. Otherwise, to keep it unchanged. This _should_ make it so the reduction in cache latency from prefetching is apparent in the reporting, if there is a lot of demand->prefetch merging in the MSHR.

I have noticed that prefetches often repeatedly issue into open MSHRs, resulting in much higher "misses" in a cache than actual packets sent downstream. This results in our cache latency reporting at something ridiculously low (like 30 or 40 cycles) due to the over-report of misses. Without prefetching, the latency returns to reasonable values like 140-170 cycles. My suggested changes to how its calculated  resolve this.

### PR DESCRIPTION
**Pull request by maccoymerrell**
Three things this pr covers:
1. Added downstream stats to the cache. This shows how many of each type of packet went downstream from said cache. This should always be <= misses, but does not count misses that hit in the mshr. It should match up with accesses to the downstream cache/dram.
2. Cache miss latency is now calculated as the total time each MSHR was open divided by the number of downstream packets (excluding writes) from that cache. If a demand merges into a prefetch, then right now it updates the open time to the demand. I am not sure if this should be done or not. I can imagine that many prefetches never get a demand merge, so this change doesn't seem too meaningful, unless we only count demands when calculating the miss latency.
3. instantiation_file.py had a bug where clock_period would not be set for operables. This was due to clock period not being a defined field within the cache, cpu, and ptw by the user. I made some modifications that should fix that issue.
resolves #535

### CODE REVIEW

**Comment by ngober** [comment]
Could you split this into multiple pull requests? I don't want comments on one to block the others. You should be able to 

    git switch develop
    git switch -c downstream_stats
    git cherry-pick -n ..cache_miss_latency_fix
    git add -p

**Comment by maccoymerrell** [comment]
I don't know exactly what I would be splitting. The downstream stats are just printing out data that is already being collected for the latency fix. I can't exactly treat them as separate, since they both depend on each other.

I might be able to move the frequency fix for the config out.

File: test/cpp/src/498-cache-plain-printer.cc [hunk 1]
```diff
@@ -8,12 +8,12 @@ TEST_CASE("An empty cache stat block prints all zeros") {
...
-    "test_cache RFO          ACCESS:          0 HIT:          0 MISS:          0",
-    "test_cache PREFETCH     ACCESS:          0 HIT:          0 MISS:          0",
-    "test_cache WRITE        ACCESS:          0 HIT:          0 MISS:          0",
-    "test_cache TRANSLATION  ACCESS:          0 HIT:          0 MISS:          0",
+    "test_cache TOTAL        ACCESS:          0 HIT:          0 MISS:          0 DOWNSTREAM:          0",
+    "test_cache LOAD         ACCESS:          0 HIT:          0 MISS:          0 DOWNSTREAM:          0",
+    "test_cache RFO          ACCESS:          0 HIT:          0 MISS:          0 DOWNSTREAM:          0",
+    "test_cache PREFETCH     ACCESS:          0 HIT:          0 MISS:          0 DOWNSTREAM:          0",
+    "test_cache WRITE        ACCESS:          0 HIT:          0 MISS:          0 DOWNSTREAM:          0",
+    "test_cache TRANSLATION  ACCESS:          0 HIT:          0 MISS:          0 DOWNSTREAM:          0",
```
Comment (ngober) [inline test/cpp/src/498-cache-plain-printer.cc:16]: I have mixed feelings about this reporting. On the one hand, I have wanted for a long time to add in some kind of "MSHR merged" indicator. On the other hand, I think that "downstream" is either not the right name or not the right statistic to be showing to the user.

This information, by your admission, is already shown in the lower-level accesses, and we shouldn't show redundant information. We get so many questions already about how to interpret these statistics that I want to make sure any changes are in the direction of increased clarity.

Comment (maccoymerrell) [reply test/cpp/src/498-cache-plain-printer.cc:16]: I think I get more questions about why misses don't equal accesses in the downstream cache more than anything else. We could report the # of merges instead, which would be misses - downstream.

Comment (ngober) [reply test/cpp/src/498-cache-plain-printer.cc:16]: I would rather do that, because that says positively what happened to each packet. However, if we simply call it `MERGED`, then the question will be "merged with what?", so we need a name like `MSHR_MERGE` or something.

**Comment by maccoymerrell** [comment]
Also, are you of the opinion that we should only be counting the latency of demand packets, and ignore the prefetch latency?
I can make a small change that would do that.

**Comment by ngober** [comment]
We definitely shouldn't count the latency for prefetches from the current level, unless it gets promoted. I think we also should not count prefetches coming from the upper level. To include them could inflate the latency if the prefetcher is bad. On the other hand, maybe because it's being averaged it won't matter.

File: config/instantiation_file.py [hunk 2]
```diff
@@ -122,6 +122,7 @@ def cache_index(name):
         '^l1i_ptr': f'(*std::next(std::begin(caches), {cache_index(cpu.get("L1I"))}))',
         '^l1d_ptr': f'(*std::next(std::begin(caches), {cache_index(cpu.get("L1D"))}))'
     }
+
```
Comment (ngober) [inline config/instantiation_file.py:125]:
```suggestion
```

**Review by ngober — APPROVED** [review]
Removing some blank lines that were the only changes in the file.
